package com.example.wayfare.Models;

public class ConversionRatesModel {
    public final Double USD;
    public final Double AED;
    public final Double AFN;
    public final Double ALL;
    public final Double AMD;
    public final Double ANG;
    public final Double AOA;
    public final Double ARS;
    public final Double AUD;
    public final Double AWG;
    public final Double AZN;
    public final Double BAM;
    public final Double BBD;
    public final Double BDT;
    public final Double BGN;
    public final Double BHD;
    public final Double BIF;
    public final Double BMD;
    public final Double BND;
    public final Double BOB;
    public final Double BRL;
    public final Double BSD;
    public final Double BTN;
    public final Double BWP;
    public final Double BYN;
    public final Double BZD;
    public final Double CAD;
    public final Double CDF;
    public final Double CHF;
    public final Double CLP;
    public final Double CNY;
    public final Double COP;
    public final Double CRC;
    public final Double CUP;
    public final Double CVE;
    public final Double CZK;
    public final Double DJF;
    public final Double DKK;
    public final Double DOP;
    public final Double DZD;
    public final Double EGP;
    public final Double ERN;
    public final Double ETB;
    public final Double EUR;
    public final Double FJD;
    public final Double FKP;
    public final Double FOK;
    public final Double GBP;
    public final Double GEL;
    public final Double GGP;
    public final Double GHS;
    public final Double GIP;
    public final Double GMD;
    public final Double GNF;
    public final Double GTQ;
    public final Double GYD;
    public final Double HKD;
    public final Double HNL;
    public final Double HRK;
    public final Double HTG;
    public final Double HUF;
    public final Double IDR;
    public final Double ILS;
    public final Double IMP;
    public final Double INR;
    public final Double IQD;
    public final Double IRR;
    public final Double ISK;
    public final Double JEP;
    public final Double JMD;
    public final Double JOD;
    public final Double JPY;
    public final Double KES;
    public final Double KGS;
    public final Double KHR;
    public final Double KID;
    public final Double KMF;
    public final Double KRW;
    public final Double KWD;
    public final Double KYD;
    public final Double KZT;
    public final Double LAK;
    public final Double LBP;
    public final Double LKR;
    public final Double LRD;
    public final Double LSL;
    public final Double LYD;
    public final Double MAD;
    public final Double MDL;
    public final Double MGA;
    public final Double MKD;
    public final Double MMK;
    public final Double MNT;
    public final Double MOP;
    public final Double MRU;
    public final Double MUR;
    public final Double MVR;
    public final Double MWK;
    public final Double MXN;
    public final Double MYR;
    public final Double MZN;
    public final Double NAD;
    public final Double NGN;
    public final Double NIO;
    public final Double NOK;
    public final Double NPR;
    public final Double NZD;
    public final Double OMR;
    public final Double PAB;
    public final Double PEN;
    public final Double PGK;
    public final Double PHP;
    public final Double PKR;
    public final Double PLN;
    public final Double PYG;
    public final Double QAR;
    public final Double RON;
    public final Double RSD;
    public final Double RUB;
    public final Double RWF;
    public final Double SAR;
    public final Double SBD;
    public final Double SCR;
    public final Double SDG;
    public final Double SEK;
    public final Double SGD;
    public final Double SHP;
    public final Double SLE;
    public final Double SLL;
    public final Double SOS;
    public final Double SRD;
    public final Double SSP;
    public final Double STN;
    public final Double SYP;
    public final Double SZL;
    public final Double THB;
    public final Double TJS;
    public final Double TMT;
    public final Double TND;
    public final Double TOP;
    public final Double TRY;
    public final Double TTD;
    public final Double TVD;
    public final Double TWD;
    public final Double TZS;
    public final Double UAH;
    public final Double UGX;
    public final Double UYU;
    public final Double UZS;
    public final Double VES;
    public final Double VND;
    public final Double VUV;
    public final Double WST;
    public final Double XAF;
    public final Double XCD;
    public final Double XDR;
    public final Double XOF;
    public final Double XPF;
    public final Double YER;
    public final Double ZAR;
    public final Double ZMW;
    public final Double ZWL;

    public ConversionRatesModel(Double usd, Double aed, Double afn, Double all, Double amd, Double ang, Double aoa, Double ars, Double aud, Double awg, Double azn, Double bam, Double bbd, Double bdt, Double bgn, Double bhd, Double bif, Double bmd, Double bnd, Double bob, Double brl, Double bsd, Double btn, Double bwp, Double byn, Double bzd, Double cad, Double cdf, Double chf, Double clp, Double cny, Double cop, Double crc, Double cup, Double cve, Double czk, Double djf, Double dkk, Double dop, Double dzd, Double egp, Double ern, Double etb, Double eur, Double fjd, Double fkp, Double fok, Double gbp, Double gel, Double ggp, Double ghs, Double gip, Double gmd, Double gnf, Double gtq, Double gyd, Double hkd, Double hnl, Double hrk, Double htg, Double huf, Double idr, Double ils, Double imp, Double inr, Double iqd, Double irr, Double isk, Double jep, Double jmd, Double jod, Double jpy, Double kes, Double kgs, Double khr, Double kid, Double kmf, Double krw, Double kwd, Double kyd, Double kzt, Double lak, Double lbp, Double lkr, Double lrd, Double lsl, Double lyd, Double mad, Double mdl, Double mga, Double mkd, Double mmk, Double mnt, Double mop, Double mru, Double mur, Double mvr, Double mwk, Double mxn, Double myr, Double mzn, Double nad, Double ngn, Double nio, Double nok, Double npr, Double nzd, Double omr, Double pab, Double pen, Double pgk, Double php, Double pkr, Double pln, Double pyg, Double qar, Double ron, Double rsd, Double rub, Double rwf, Double sar, Double sbd, Double scr, Double sdg, Double sek, Double sgd, Double shp, Double sle, Double sll, Double sos, Double srd, Double ssp, Double stn, Double syp, Double szl, Double thb, Double tjs, Double tmt, Double tnd, Double top, Double aTry, Double ttd, Double tvd, Double twd, Double tzs, Double uah, Double ugx, Double uyu, Double uzs, Double ves, Double vnd, Double vuv, Double wst, Double xaf, Double xcd, Double xdr, Double xof, Double xpf, Double yer, Double zar, Double zmw, Double zwl) {
        USD = usd;
        AED = aed;
        AFN = afn;
        ALL = all;
        AMD = amd;
        ANG = ang;
        AOA = aoa;
        ARS = ars;
        AUD = aud;
        AWG = awg;
        AZN = azn;
        BAM = bam;
        BBD = bbd;
        BDT = bdt;
        BGN = bgn;
        BHD = bhd;
        BIF = bif;
        BMD = bmd;
        BND = bnd;
        BOB = bob;
        BRL = brl;
        BSD = bsd;
        BTN = btn;
        BWP = bwp;
        BYN = byn;
        BZD = bzd;
        CAD = cad;
        CDF = cdf;
        CHF = chf;
        CLP = clp;
        CNY = cny;
        COP = cop;
        CRC = crc;
        CUP = cup;
        CVE = cve;
        CZK = czk;
        DJF = djf;
        DKK = dkk;
        DOP = dop;
        DZD = dzd;
        EGP = egp;
        ERN = ern;
        ETB = etb;
        EUR = eur;
        FJD = fjd;
        FKP = fkp;
        FOK = fok;
        GBP = gbp;
        GEL = gel;
        GGP = ggp;
        GHS = ghs;
        GIP = gip;
        GMD = gmd;
        GNF = gnf;
        GTQ = gtq;
        GYD = gyd;
        HKD = hkd;
        HNL = hnl;
        HRK = hrk;
        HTG = htg;
        HUF = huf;
        IDR = idr;
        ILS = ils;
        IMP = imp;
        INR = inr;
        IQD = iqd;
        IRR = irr;
        ISK = isk;
        JEP = jep;
        JMD = jmd;
        JOD = jod;
        JPY = jpy;
        KES = kes;
        KGS = kgs;
        KHR = khr;
        KID = kid;
        KMF = kmf;
        KRW = krw;
        KWD = kwd;
        KYD = kyd;
        KZT = kzt;
        LAK = lak;
        LBP = lbp;
        LKR = lkr;
        LRD = lrd;
        LSL = lsl;
        LYD = lyd;
        MAD = mad;
        MDL = mdl;
        MGA = mga;
        MKD = mkd;
        MMK = mmk;
        MNT = mnt;
        MOP = mop;
        MRU = mru;
        MUR = mur;
        MVR = mvr;
        MWK = mwk;
        MXN = mxn;
        MYR = myr;
        MZN = mzn;
        NAD = nad;
        NGN = ngn;
        NIO = nio;
        NOK = nok;
        NPR = npr;
        NZD = nzd;
        OMR = omr;
        PAB = pab;
        PEN = pen;
        PGK = pgk;
        PHP = php;
        PKR = pkr;
        PLN = pln;
        PYG = pyg;
        QAR = qar;
        RON = ron;
        RSD = rsd;
        RUB = rub;
        RWF = rwf;
        SAR = sar;
        SBD = sbd;
        SCR = scr;
        SDG = sdg;
        SEK = sek;
        SGD = sgd;
        SHP = shp;
        SLE = sle;
        SLL = sll;
        SOS = sos;
        SRD = srd;
        SSP = ssp;
        STN = stn;
        SYP = syp;
        SZL = szl;
        THB = thb;
        TJS = tjs;
        TMT = tmt;
        TND = tnd;
        TOP = top;
        TRY = aTry;
        TTD = ttd;
        TVD = tvd;
        TWD = twd;
        TZS = tzs;
        UAH = uah;
        UGX = ugx;
        UYU = uyu;
        UZS = uzs;
        VES = ves;
        VND = vnd;
        VUV = vuv;
        WST = wst;
        XAF = xaf;
        XCD = xcd;
        XDR = xdr;
        XOF = xof;
        XPF = xpf;
        YER = yer;
        ZAR = zar;
        ZMW = zmw;
        ZWL = zwl;
    }

}

